name: .NET

on:
  push:
    branches: [ main ]
env:
  PUBLISH_PATH: '.'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release -o '${{env.PUBLISH_PATH}}/publish'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: published artifact
        path: publish
        
        
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download built artifact
      uses: actions/download-artifact@v2
      with:
        name: published artifact
        path: publish
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: marvelamar/SampleDotnetApp/MyApp
        tag_with_sha: true
